new-session  
setw -g mode-mouse on  
set -g history-limit 30000
set -g default-terminal screen-256color
bind V split-window -h
bind H split-window
bind r source-file ~/.tmux.conf \; display "Reloaded config"
